# Generated by Django 2.2.4 on 2019-08-29 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_pcs', models.IntegerField()),
                ('price', models.IntegerField()),
                ('shop_id', models.CharField(max_length=20)),
                ('vip', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('price', models.IntegerField()),
                ('shop_id', models.CharField(blank=True, max_length=20, null=True)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.ProductList')),
            ],
        ),
    ]
